global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter-local'
    static_configs:
      - targets: ['node-exporter-monitoring:9100']

  # SERVIDOR WINDOWS - usando Windows Exporter na porta 9182
  - job_name: 'servidor-windows-196'
    static_configs:
      - targets: ['10.1.1.196:9182']
    labels:
      group: 'windows-servers'
      instance: 'servidor-windows-196'

  # SERVIDOR GLPI - usando Node Exporter na porta 9100
  - job_name: 'servidor-glpi'
    static_configs:
      - targets: ['172.17.17.30:9100']
    labels:
      group: 'linux-servers'
      instance: 'servidor-glpi'

  # Adicione mais servidores aqui conforme necess√°rio
  # - job_name: 'outro-servidor'
  #   static_configs:
  #     - targets: ['IP:PORTA']
