global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'servidor-local'
      - targets: ['172.17.17.30:9100']
        labels:
          instance: 'glpi-server'

  - job_name: 'windows-exporter'
    static_configs:
      - targets: ['10.1.1.196:9182']
        labels:
          instance: 'windows-server'
          os: 'windows'
