scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'servidor-local'
      - targets: ['host.docker.internal:9100']  # ← Alterado
        labels:
          instance: 'glpi-server'

  - job_name: 'windows-exporter'
    static_configs:
      - targets: ['host.docker.internal:9182']  # ← Alterado
        labels:
          instance: 'windows-server'
          os: 'windows'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']